# Generated by Django 4.0.1 on 2022-01-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_tags',
            field=models.ManyToManyField(blank=True, to='products.Tag'),
        ),
    ]
